### ISSUE TITLE
argon2-cli not argon2 or node-argon2-cli

### ISSUE THREAD

**Issue by favna** [ranisalt/node-argon2-cli#22] opened 2018-04-06 14:58 UTC
The package is registered as `argon2-cli` in the package.json, not as `node-argon2-cli` nor `argon2`. I highly recommend rectifying this in the readme and renaming the repository accordingly because as it is you're using 3 different naming across the board. Personally i recommend naming this repo and `argon2` and naming the JS module `node-argon2`. People will then do `npm install --global argon2` to install the CLI version or `npm install node-argon2` to install the JS module (and use `require('node-argon2')`)

### Steps to reproduce
1. Fresh install package (preferably on windows)
2. Try to run `argon2 -h`
3. Notice that it'll say `argon2: command not found`

### Expected behaviour
Tell us what should happen

Expected output is:
```bash
usage: argon2 salt [-d] [-t iterations] [-m memory] [-p parallelism]
        Password is read from stdin

Positional arguments:
  salt

Optional arguments:
  -h, --help     Show this help message and exit.
  -d, --argon2d  Use Argon2d instead of Argon2i (default: false)
  -m N           Sets the memory usage to 2^N KiB (default: 12)
  -t N           Sets the number of iterations to N (default: 3)
  -p N           Sets parallelism to N threads (default: 1)
  -q             Do not output timing information (default: false)
```

### Actual behaviour
Tell us what happens instead

Literally nothing.

### Environment
**Operating system:** Windows 10

**Node version:** 8.11.1

**Compiler version:** latest windows-build-tools whichever that may be

**Comment by ranisalt** [comment] 2018-04-06 18:30
I disagree. A package named `argon2` coming from npm/yarn is, at first look, a module, not a cli tool. Appending `-cli` fixes that ambiguity.

This package name follows what most major libraries do, e.g. babel, lodash and gulp. I'd rather rename the executable to `argon2-cli` than swap names.

**Comment by favna** [comment] 2018-04-06 19:18
Sorry but you misunderstand. I agree that keeping the name argon2-cli is correct, but then the readme also has to say that for the instructions.

**Comment by AlexGustafsson** [comment] 2019-03-26 18:30
@Favna is correct. It's installed as `argon2-cli`, not `argon2` as specified in the examples in the readme. If this is intended behaviour, the readme should probably be updated.

**Comment by msheakoski** [comment] 2019-11-11 17:23
Please take a look at PR #24. I updated the README with the following changes:
* use `argon2-cli` instead of `argon2`
* replace all of the output with what the latest version generates
* update the deprecated `-q` flag to `-e`
* fix the memory usage example to use `-k` instead of `-m` because `-m` does not seem to change anything

**Comment by ranisalt** [comment] 2019-11-11 18:43
Now I get it. I merged the PR fixing this issue, but I would recommend against using this tool if your distro provides `argon2` (I'm on Arch Linux and it does), since this package is only a rewrite for when it is unavailable. I think most distros now ship `argon2` so argon2-cli shouldn't be needed.

**Closed as completed by ranisalt** 2019-11-11 18:43 UTC

**Comment by msheakoski** [comment] 2019-11-11 19:13
@ranisalt Ahh, I did not realize that was an option. I will make another PR when I have a chance that adds some suggestions for linux/mac provided by the distro.
